config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'surveys#index'
  resources :surveys, only: %i[index new create] do
    resources :survey_responses, only: %i[new create]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base

  primary_abstract_class

end

app/models/survey.rb
# frozen_string_literal: true

class Survey < ApplicationRecord

  has_many :survey_responses, dependent: :destroy
  has_one :survey_result, dependent: :destroy

end

app/models/survey_response.rb
# frozen_string_literal: true

class SurveyResponse < ApplicationRecord

  belongs_to :survey

end

app/models/survey_result.rb
# frozen_string_literal: true

class SurveyResult < ApplicationRecord

  belongs_to :survey

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/concerns/rescue_errors.rb
# frozen_string_literal: true

module RescueErrors
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordInvalid, with: :handle_record_invalid
    rescue_from ActiveModel::ValidationError, with: :handle_validation_error
  end

  private

  def handle_record_invalid(exception)
    redirect_back fallback_location: root_path,
                  alert: "There was an error with your submission: #{exception.record.errors.full_messages.join(', ')}"
  end

  def handle_validation_error(exception)
    redirect_back fallback_location: root_path,
                  alert: "There was an error with your submission: #{exception.model.errors.full_messages.join(', ')}"
  end
end

app/controllers/survey_responses_controller.rb
# frozen_string_literal: true

class SurveyResponsesController < ApplicationController

  include RescueErrors

  def new
    @survey = Survey.find(params[:survey_id])
    @survey_response = SurveyResponse.new
  end

  def create
    ActiveRecord::Base.transaction do
      CreateSurveyResponse::EntryPoint.call(survey_id: params[:survey_id], params: survey_response_params)
    end

    redirect_to surveys_path, notice: 'Thank you for taking this survey.'
  end

  private

  def survey_response_params
    params.require(:survey_response).permit(:answer).to_h
  end

end

app/controllers/surveys_controller.rb
# frozen_string_literal: true

class SurveysController < ApplicationController

  include RescueErrors

  def index
    @surveys = Survey.all.includes(:survey_result).page(params[:page]).per(30)
  end

  def new
    @survey = Survey.new
  end

  def create
    ActiveRecord::Base.transaction { CreateSurvey::EntryPoint.call(params: survey_params) }

    redirect_to surveys_path, notice: 'Survey was successfully created.'
  end

  private

  def survey_params
    params.require(:survey).permit(:question).to_h
  end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/survey_responses_helper.rb
# frozen_string_literal: true

module SurveyResponsesHelper
end

app/helpers/surveys_helper.rb
# frozen_string_literal: true

module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleSurvey</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="bg-gray-50">
      <div class="min-h-screen flex flex-col">
        <% if flash[:notice] %>
          <div class="flex items-center justify-center w-screen">
            <div class="w-full bg-green-500 py-8 flex justify-center">
              <h1 class="text-white text-2xl font-semibold text-center"> <%= flash[:notice] %> </h1>
            </div>
          </div>
        <% end %>

        <% if flash[:alert] %>
          <div class="flex items-center justify-center w-screen">
            <div class="w-full bg-red-500 py-8 flex justify-center">
              <h1 class="text-white text-2xl font-semibold text-center"> <%= flash[:alert] %> </h1>
            </div>
          </div>
        <% end %>

        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/shared/_back_button.html.erb
<div class="absolute top-4 left-4 md:top-8 md:left-8">
  <%= link_to back_path do %>
    <svg class="w-8 h-8 md:w-10 md:h-10 text-gray-600 hover:text-gray-800" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
    </svg>
  <% end %>
</div>

app/views/survey_responses/_form.html.erb
<div class="w-full max-w-4xl">
  <h1 class="text-4xl font-bold text-green-600 text-center mb-12"><%= survey.question %></h1>

  <%= form_with model: [survey, survey_response], local: true do |form| %>
    <%= form.hidden_field :answer, value: "" %>
    <div class="flex justify-center mb-12">
      <label class="inline-flex items-center mr-6 cursor-pointer">
        <%= form.radio_button :answer, true, class: 'form-radio text-green-600 cursor-pointer' %>
        <span class="ml-2 text-2xl">Yes</span>
      </label>
      <label class="inline-flex items-center cursor-pointer">
        <%= form.radio_button :answer, false, class: 'form-radio text-red-600 cursor-pointer' %>
        <span class="ml-2 text-2xl">No</span>
      </label>
    </div>

    <div class="flex justify-center">
      <%= form.submit 'Submit', class: 'bg-green-600 text-white font-semibold py-3 px-8 rounded-lg hover:bg-green-700 cursor-pointer text-2xl' %>
    </div>
  <% end %>
</div>

app/views/survey_responses/new.html.erb
<div class="bg-gray-100 flex flex-col justify-center items-center h-screen p-8">
  <%= render 'shared/back_button', back_path: surveys_path %>

  <%= render 'form', survey: @survey, survey_response: @survey_response %>
</div>

app/views/surveys/_form.html.erb
<div class="w-full max-w-3xl md:max-w-6xl p-8 md:p-16 h-full flex flex-col justify-center">
  <h1 class="text-3xl md:text-5xl font-bold text-center text-green-600 mb-8 md:mb-12"><%= form_title %></h1>
  <%= form_with model: @survey, local: true do |form| %>
    <div class="mb-8 md:mb-12">
      <%= form.label :question, class: 'block text-gray-700 font-semibold mb-4 md:mb-6 text-lg md:text-2xl' %>
      <%= form.text_area :question, placeholder: "Enter your survey question here...", rows: 3, class: 'form-textarea mt-1 block w-full text-center text-xl md:text-3xl rounded-md border-gray-300 shadow-lg focus:border-green-500 focus:ring focus:ring-green-200 focus:ring-opacity-50 placeholder-gray-500 placeholder-opacity-100 resize-none overflow-hidden' %>
    </div>

    <div class="flex justify-center mt-4 md:mt-8">
      <%= form.submit submit_button_text, class: 'bg-green-600 text-white font-semibold py-3 md:py-4 px-6 md:px-10 rounded-md hover:bg-green-700 hover:shadow-xl cursor-pointer text-lg md:text-2xl' %>
    </div>
  <% end %>
</div>

app/views/surveys/_header.html.erb
<div class="flex justify-between items-center mb-6">
  <h1 class="text-3xl font-bold">Surveys</h1>
  <%= link_to 'Create New Survey', new_survey_path, class: 'bg-green-500 text-white py-2 px-4 rounded' %>
</div>

app/views/surveys/_survey_card.html.erb
<div class="w-full md:w-1/2 lg:w-1/3 lg:min-w-[300px] px-4 mb-6">
  <div class="bg-white border border-gray-300 rounded-lg p-6 flex flex-col h-full">
    <h2 class="text-xl font-semibold mb-2"><%= survey.question %></h2>
    <p class="text-gray-500 mb-4">Modified <%= survey.updated_at.strftime("%m/%d/%Y") %></p>
    <p class="text-gray-500 font-semibold mb-4 inline-flex items-center">
      Responses: <%= survey.survey_result.responses_count %>
    </p>
    <%= pie_chart Decorators::SurveyResult.new(survey.survey_result).pie_chart, colors: ["#4CAF50", "#F44336"], legend: "bottom" %>
    <%= link_to 'Start Survey', new_survey_survey_response_path(survey), class: 'w-full border border-gray-300 text-gray-700 py-2 rounded-md hover:bg-gray-100 block text-center mt-4 mt-auto' %>
  </div>
</div>

app/views/surveys/index.html.erb
<div class="flex-1 max-w-7xl mx-auto p-8">
  <%= render 'header' %>

  <div class="flex flex-wrap -mx-4">
    <%= render partial: 'survey_card', collection: @surveys, as: :survey  %>
  </div>

  <div class="mt-4 text-center">
    <%= paginate @surveys %>
  </div>
</div>

app/views/surveys/new.html.erb
<div class="bg-gray-50 flex flex-col justify-center items-center min-h-screen p-4 md:p-12">
  <%= render 'shared/back_button', back_path: surveys_path %>

  <%= render 'surveys/form', form_title: 'Create New Survey', submit_button_text: 'Create Survey' %>
</div>